# Generated by Django 6.0.5 on 2026-05-14 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('kategori_id', models.AutoField(primary_key=True, serialize=False)),
                ('kategori_adi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('marka_id', models.AutoField(primary_key=True, serialize=False)),
                ('marka_adi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_adi', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('urun_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_adi', models.CharField(max_length=255)),
                ('model_kodu', models.CharField(blank=True, max_length=255, null=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.kategori')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.marka')),
            ],
        ),
        migrations.CreateModel(
            name='AiUrunOzeti',
            fields=[
                ('ozet_id', models.AutoField(primary_key=True, serialize=False)),
                ('genel_ozet_metni', models.TextField()),
                ('genel_duygu_ortalamasi', models.FloatField()),
                ('son_guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('urun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzer.urun')),
            ],
        ),
        migrations.CreateModel(
            name='UrunAnalizDetayi',
            fields=[
                ('detay_id', models.AutoField(primary_key=True, serialize=False)),
                ('analiz_konusu', models.CharField(max_length=255)),
                ('konu_puani', models.FloatField()),
                ('konu_ozeti', models.TextField()),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.urun')),
            ],
        ),
        migrations.CreateModel(
            name='UrunPlatformHaritası',
            fields=[
                ('harita_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_urun_url', models.URLField()),
                ('platform_urun_id', models.CharField(max_length=255)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.platform')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.urun')),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('yorum_id', models.AutoField(primary_key=True, serialize=False)),
                ('yorum_metni', models.TextField()),
                ('verilen_puan', models.IntegerField(blank=True, null=True)),
                ('yorum_tarihi', models.DateField()),
                ('duygu_skoru', models.FloatField(blank=True, null=True)),
                ('harita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.urunplatformharitası')),
            ],
        ),
    ]
