# Generated by Django 6.0.5 on 2026-05-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiurunozeti',
            name='genel_duygu_ortalamasi',
            field=models.FloatField(blank=True, db_column='genel_duygu_ortalamasi', null=True),
        ),
        migrations.AlterField(
            model_name='aiurunozeti',
            name='genel_ozet_metni',
            field=models.TextField(blank=True, db_column='genel_ozet_metni', null=True),
        ),
        migrations.AlterField(
            model_name='aiurunozeti',
            name='ozet_id',
            field=models.AutoField(db_column='ozet_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiurunozeti',
            name='son_guncelleme_tarihi',
            field=models.DateField(auto_now=True, db_column='son_guncelleme_tarihi'),
        ),
        migrations.AlterField(
            model_name='aiurunozeti',
            name='urun',
            field=models.OneToOneField(db_column='urun_id', on_delete=django.db.models.deletion.CASCADE, to='analyzer.urun'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='kategori_adi',
            field=models.CharField(db_column='kategori_adi', max_length=255),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='kategori_id',
            field=models.AutoField(db_column='kategori_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marka',
            name='marka_adi',
            field=models.CharField(db_column='marka_adi', max_length=255),
        ),
        migrations.AlterField(
            model_name='marka',
            name='marka_id',
            field=models.AutoField(db_column='marka_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platform',
            name='base_url',
            field=models.CharField(blank=True, db_column='base_url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_adi',
            field=models.CharField(db_column='platform_adi', max_length=100),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_id',
            field=models.AutoField(db_column='platform_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.ForeignKey(db_column='kategori_id', on_delete=django.db.models.deletion.CASCADE, to='analyzer.kategori'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='marka',
            field=models.ForeignKey(db_column='marka_id', on_delete=django.db.models.deletion.CASCADE, to='analyzer.marka'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='model_adi',
            field=models.CharField(db_column='model_adi', max_length=255),
        ),
        migrations.AlterField(
            model_name='urun',
            name='model_kodu',
            field=models.CharField(blank=True, db_column='model_kodu', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urun_id',
            field=models.AutoField(db_column='urun_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urunanalizdetayi',
            name='analiz_konusu',
            field=models.CharField(blank=True, db_column='analiz_konusu', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urunanalizdetayi',
            name='detay_id',
            field=models.AutoField(db_column='detay_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urunanalizdetayi',
            name='konu_ozeti',
            field=models.TextField(blank=True, db_column='konu_ozeti', null=True),
        ),
        migrations.AlterField(
            model_name='urunanalizdetayi',
            name='konu_puani',
            field=models.FloatField(blank=True, db_column='konu_puani', null=True),
        ),
        migrations.AlterField(
            model_name='urunanalizdetayi',
            name='urun',
            field=models.ForeignKey(db_column='urun_id', on_delete=django.db.models.deletion.CASCADE, to='analyzer.urun'),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='duygu_skoru',
            field=models.FloatField(blank=True, db_column='duygu_skoru', null=True),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='verilen_puan',
            field=models.IntegerField(blank=True, db_column='verilen_puan', null=True),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='yorum_id',
            field=models.AutoField(db_column='yorum_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='yorum_metni',
            field=models.TextField(blank=True, db_column='yorum_metni', null=True),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='yorum_tarihi',
            field=models.DateField(blank=True, db_column='yorum_tarihi', null=True),
        ),
        migrations.AlterModelTable(
            name='aiurunozeti',
            table='AI_URUN_OZETLERI',
        ),
        migrations.AlterModelTable(
            name='kategori',
            table='KATEGORILER',
        ),
        migrations.AlterModelTable(
            name='marka',
            table='MARKALAR',
        ),
        migrations.AlterModelTable(
            name='platform',
            table='PLATFORMLAR',
        ),
        migrations.AlterModelTable(
            name='urun',
            table='URUNLER',
        ),
        migrations.AlterModelTable(
            name='urunanalizdetayi',
            table='URUN_ANALIZ_DETAYLARI',
        ),
        migrations.AlterModelTable(
            name='yorum',
            table='YORUMLAR',
        ),
        migrations.CreateModel(
            name='UrunPlatformHaritasi',
            fields=[
                ('harita_id', models.AutoField(db_column='harita_id', primary_key=True, serialize=False)),
                ('platform_urun_url', models.TextField(blank=True, db_column='platform_urun_url', null=True)),
                ('platform_urun_id', models.CharField(blank=True, db_column='platform_urun_id', max_length=100, null=True)),
                ('platform', models.ForeignKey(db_column='platform_id', on_delete=django.db.models.deletion.CASCADE, to='analyzer.platform')),
                ('urun', models.ForeignKey(db_column='urun_id', on_delete=django.db.models.deletion.CASCADE, to='analyzer.urun')),
            ],
            options={
                'db_table': 'URUN_PLATFORM_HARITASI',
            },
        ),
        migrations.AlterField(
            model_name='yorum',
            name='harita',
            field=models.ForeignKey(db_column='harita_id', on_delete=django.db.models.deletion.CASCADE, to='analyzer.urunplatformharitasi'),
        ),
        migrations.DeleteModel(
            name='UrunPlatformHaritası',
        ),
    ]
